In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import Library yang diperlukan

In [3]:
dataset = pd.read_csv('DataTransferPlayer.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

untuk mengambil semua baris
Untuk mengambil dan membaca dataset

In [4]:
print(x)

[['ManchesterRed' 32000000.0 86.0]
 ['ManchesterBlue' 39000000.0 83.0]
 ['NorthLondon' nan 86.0]
 ['NorthLondon' 80000000.0 nan]
 ['ManchesterRed' 40000000.0 69.0]
 ['NorthLondon' 45000000.0 85.0]
 ['ManchesterBlue' 40000000.0 nan]
 ['ManchesterRed' 39000000.0 80.0]
 ['ManchesterBlue' 56000000.0 82.0]
 ['ManchesterRed' 80000000.0 85.0]]


In [5]:
print(y)

['Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

library machine learning untuk mengisi data kosong dengan mean/modus/mean.(SimpleImputer)
: , 1:3 = ambil semua baris, ambil komlom 1 sampai 3

In [7]:
print(x)

[['ManchesterRed' 32000000.0 86.0]
 ['ManchesterBlue' 39000000.0 83.0]
 ['NorthLondon' 50111111.11111111 86.0]
 ['NorthLondon' 80000000.0 82.0]
 ['ManchesterRed' 40000000.0 69.0]
 ['NorthLondon' 45000000.0 85.0]
 ['ManchesterBlue' 40000000.0 82.0]
 ['ManchesterRed' 39000000.0 80.0]
 ['ManchesterBlue' 56000000.0 82.0]
 ['ManchesterRed' 80000000.0 85.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

untuk data polinominal yang jenisnya lebih dari 2 harus diencoding dulu, dan akan dibuat menjadi matriks

In [9]:
print(x)

[[0.0 1.0 0.0 32000000.0 86.0]
 [1.0 0.0 0.0 39000000.0 83.0]
 [0.0 0.0 1.0 50111111.11111111 86.0]
 [0.0 0.0 1.0 80000000.0 82.0]
 [0.0 1.0 0.0 40000000.0 69.0]
 [0.0 0.0 1.0 45000000.0 85.0]
 [1.0 0.0 0.0 40000000.0 82.0]
 [0.0 1.0 0.0 39000000.0 80.0]
 [1.0 0.0 0.0 56000000.0 82.0]
 [0.0 1.0 0.0 80000000.0 85.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print(y)

[1 0 0 1 1 1 0 0 1 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

input x, label y

In [13]:
print(x_train)

[[1.0 0.0 0.0 40000000.0 82.0]
 [0.0 1.0 0.0 40000000.0 69.0]
 [0.0 1.0 0.0 32000000.0 86.0]
 [0.0 0.0 1.0 80000000.0 82.0]
 [1.0 0.0 0.0 39000000.0 83.0]
 [0.0 1.0 0.0 39000000.0 80.0]
 [1.0 0.0 0.0 56000000.0 82.0]
 [0.0 0.0 1.0 45000000.0 85.0]]


karena test size 0.2 maka data dikurang 2 menjadi 8

In [14]:
print(x_test)

[[0.0 0.0 1.0 50111111.11111111 86.0]
 [0.0 1.0 0.0 80000000.0 85.0]]


In [15]:
print(y_train)

[0 1 1 1 0 0 1 1]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

3: adalah 3 sampai akhir (karena matriks ordo 3)

In [18]:
print(x_train)

[[1.0 0.0 0.0 -0.44773030693227 0.1782030270768846]
 [0.0 1.0 0.0 -0.44773030693227 -2.4693848037796866]
 [0.0 1.0 0.0 -1.0095879470041382 0.9928454365712143]
 [0.0 0.0 1.0 2.3615578934270713 0.1782030270768846]
 [1.0 0.0 0.0 -0.5179625119412535 0.38186362945046703]
 [0.0 1.0 0.0 -0.5179625119412535 -0.2291181776702802]
 [1.0 0.0 0.0 0.6759849732114666 0.1782030270768846]
 [0.0 0.0 1.0 -0.09656928188735237 0.7891848341976319]]


In [20]:
print(x_test)

[[0.0 0.0 1.0 0.26239532149189687 0.9928454365712143]
 [0.0 1.0 0.0 2.3615578934270713 0.7891848341976319]]
